; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "NFC Service"
#define MyAppVersion "1.0"
#define MyAppPublisher "NFC Solutions"
#define MyAppExeName "nfc-service.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8F4A2C1B-E3D5-4F6A-9B8C-7D0E1F2A3B4C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={commonpf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=Instalador_NFC_Service
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Files]
; Archivo principal y scripts
Source: "nfc-service.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "nfc-service.js"; DestDir: "{app}"; Flags: ignoreversion
Source: "package.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "nfc-service-oculto.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "instalar-servicio.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "desinstalar-servicio.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "console.html"; DestDir: "{app}"; Flags: ignoreversion

; Carpeta node (node_modules)
Source: "node_modules\*"; DestDir: "{app}\node_modules"; Flags: ignoreversion recursesubdirs createallsubdirs

; Archivos del Driver (se copian a temporal para instalar)
Source: "ACS_Unified_Driver_MSI_Win_4280_P\*"; DestDir: "{tmp}\Driver"; Flags: ignoreversion recursesubdirs createallsubdirs

[Run]
; Paso 1: Instalar Driver (Interactivo)
Filename: "{tmp}\Driver\Setup.exe"; StatusMsg: "Ejecutando instalador de controladores..."; Flags: waituntilterminated

; Paso 2: Correr servidor (instalar servicio)
; Se ejecuta visible porque el bat tiene 'pause' y muestra info importante
Filename: "{app}\instalar-servicio.bat"; StatusMsg: "Registrando e iniciando el servicio..."; Flags: waituntilterminated

; Paso 3: Abrir consola de verificación (al finalizar)
Filename: "{app}\console.html"; Description: "Abrir consola de verificación"; Flags: postinstall shellexec nowait

[UninstallRun]
; Ejecutar desinstalador del servicio antes de borrar archivos
; Primero detener el proceso si está corriendo
Filename: "taskkill.exe"; Parameters: "/F /IM nfc-service.exe /T"; Flags: runhidden waituntilterminated; RunOnceId: "StopService"
; Luego ejecutar el script de desinstalación
Filename: "{app}\desinstalar-servicio.bat"; Flags: waituntilterminated runhidden; RunOnceId: "DelService"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\console.html"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\console.html"; Tasks: desktopicon

